env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
    main: ./cmd/n26
    binary: n26

archives:
  - format: zip
    name_template: "{{ .ProjectName }}-cli-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    files:
      - none*

release:
  github:
    owner: jjbeto
    name: n26
  name_template: "{{.Version}}"

checksum:
  name_template: checksums.txt

brews:
  -
    name: n26
    tap:
      owner: jjbeto
      name: homebrew-tools
    homepage: https://github.com/jjbeto/n26
    description: CLI tool for N26 Bank
    test: |
      system "#{bin}/n26", "--version"
